In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr2=arr1.reshape((1,5))

In [9]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [11]:
np.arange(0,10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
print(arr2.ndim)
print(arr2.dtype)

2
int64


In [19]:
arr2=np.arange(0,10)

In [20]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [23]:
arr=np.arange(1,31).reshape((5,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [24]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [28]:
arr[0,1]

np.int64(2)

In [29]:
arr[1:4,4:]

array([[11, 12],
       [17, 18],
       [23, 24]])

In [30]:
arr=np.arange(1,11)

In [31]:
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_data=(arr-mean)/std_dev
print(normalized_data)

[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [32]:
arr=np.array([1,2,3,4,5]) 
print(np.pow(arr,2))

[ 1  4  9 16 25]


In [33]:
arr>2

array([False, False,  True,  True,  True])

In [38]:
arr[(arr>2) & (arr<5)]

array([3, 4])

In [1]:
import pandas as pd

In [3]:
data=[1,2,3,4,5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
dict={"name":"jai","rollno":10690}
pd.Series(dict)

name        jai
rollno    10690
dtype: object

In [5]:
ind=['a','b','c','d','e']
pd.Series(data,index=ind)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
data={
    "NAME":['jaideep','raja','gudia'],
    'age':[22,32,31],
    'city':["ranchi","lucknow","bareilly"]
}
pd.DataFrame(data)

,NAME,age,city
0,jaideep,22,ranchi
1,raja,32,lucknow
2,gudia,31,bareilly


In [11]:
df=pd.read_csv(r"../dataForPracc/sales_data.csv")
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal


In [16]:
data={
    "NAME":['jaideep','raja','gudia'],
    'age':[22,32,31],
    'city':["ranchi","lucknow","bareilly"]
}
pp=pd.DataFrame(data)

In [17]:
pp["NAME"]

0    jaideep
1       raja
2      gudia
Name: NAME, dtype: str

In [18]:
pp.loc[0]

NAME    jaideep
age          22
city     ranchi
Name: 0, dtype: object

In [19]:
pp.at[1,"NAME"]

'raja'

In [20]:
pp["salary"]=[20,40,50]
pp

,NAME,age,city,salary
0,jaideep,22,ranchi,20
1,raja,32,lucknow,40
2,gudia,31,bareilly,50


In [22]:
pp.drop("salary",axis=1,inplace=True)

In [23]:
pp["age"]=pp["age"]+1
pp

,NAME,age,city
0,jaideep,23,ranchi
1,raja,33,lucknow
2,gudia,32,bareilly


In [25]:
pp.drop(0)

,NAME,age,city
1,raja,33,lucknow
2,gudia,32,bareilly


In [26]:
pp.describe()

,age
count,3.000000
mean,29.333333
std,5.507571
min,23.000000
25%,27.500000
50%,32.000000
75%,32.500000
max,33.000000


In [30]:
df=pd.read_csv("../dataForPracc/data.csv")
df.head()

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North


In [31]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [33]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [34]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [36]:
df.fillna(0)

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North
5,2023-01-06,B,54.0,Product3,192.0,West
6,2023-01-07,A,16.0,Product1,936.0,East
7,2023-01-08,C,89.0,Product1,488.0,West
8,2023-01-09,C,37.0,Product3,772.0,West
9,2023-01-10,A,22.0,Product2,834.0,West


In [40]:
df["sales_fill"]=df["Sales"].fillna(df["Sales"].mean())
df.head()

,Date,Category,Value,Product,Sales,Region,sales_fill
0,2023-01-01,A,28.0,Product1,754.0,East,754.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0


In [44]:
df=df.rename(columns={"Date":"date"})
df.head()

,date,Category,Value,Product,Sales,Region,sales_fill
0,2023-01-01,A,28.0,Product1,754.0,East,754.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0


In [48]:
df["Value_new"]=df["Value"].fillna(df["Value"].mean()).astype(int)
df.head()

,date,Category,Value,Product,Sales,Region,sales_fill,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26


In [51]:
df["Value_new"]=df["Value"].apply(lambda x:x*2)
df.head()

,date,Category,Value,Product,Sales,Region,sales_fill,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,52.0


In [52]:
grouped_mean=df.groupby("Product")["Value"].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64


In [53]:
df.groupby(["Product","Region"])["Value"].sum()


Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [54]:
df.groupby("Region")["Value"].agg(["sum","mean","count"])

,sum,mean,count
Region,,,
East,550.0,42.307692,13
North,339.0,37.666667,9
South,496.0,62.000000,8
West,1047.0,61.588235,17


In [55]:
### Merging and Joining DataFrames

# Create sample DataFrames
df1 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'Key': ['A', 'B', 'D'],
    'Value2': [4, 5, 6]
})


In [56]:
df1

,Key,Value1
0,A,1
1,B,2
2,C,3


In [57]:
df2

,Key,Value2
0,A,4
1,B,5
2,D,6


In [59]:
pd.merge(df1,df2,on="Key",how="inner")

,Key,Value1,Value2
0,A,1,4
1,B,2,5


In [60]:
pd.merge(df1,df2,on="Key",how="outer")

,Key,Value1,Value2
0,A,1.0,4.0
1,B,2.0,5.0
2,C,3.0,NaN
3,D,NaN,6.0


In [62]:
pd.merge(df1,df2,on="Key",how="left")

,Key,Value1,Value2
0,A,1,4.0
1,B,2,5.0
2,C,3,NaN
